### ISSUE TITLE
Syllabus does not have dates for each week's class

### ISSUE THREAD

**Issue by decause** [decause/hflossk#172]
This is a complex problem because:
- I want the week system to be date-agnostic, so that it can be spun up for other courses in other semesters
- But I want to not have to compute the due-dates for every assignment myself...

Perhaps a text/yaml file somewhere, with a map of weeks to dates, is in order? I think this is a good middle ground.

```
'wXcY': 'DD-MM-YYYY' 
```

@DAWacker this is for you :)

**Comment by h2g2guy** [comment]
Wouldn't a better solution be to have a start date and a week schedule, and automatically calculate the dates, with exceptions for holidays/reschedulings?  This way you could have a 4-5 line text/yaml instead of a repetitive 30 line one.

**Comment by Qalthos** [comment]
closed as per #175
