### ISSUE TITLE
Scrapper misreading blogs

### ISSUE THREAD

**Issue by Destroyer675000** [decause/hflossk#182]
There is an issue with a majority of all students blog post numbers and they need to update the amount of Syndication feeds show the most recent located in the Reading section in Settings. If  there are any questions ask Destroyer675000

**Comment by decause** [comment]
@Destroyer675000 good catch!

Likely, the fix will be adding some instructions for users on how to change the default number of posts that show up in their RSS feed. This should be added as a section to the First Flight Assignment: https://github.com/decause/hflossk/blob/master/hflossk/templates/hw/firstflight.mak

**Comment by liam-middlebrook** [comment]
There's an existing blog post documenting how to solve this issue. Later tonight I'll go through and add it to the first flight.

http://brendanwhitfield.wordpress.com/2014/04/21/expanding-the-wordpress-rss-feed/

**Comment by decause** [comment]
@liam-middlebrook did this ever make it upstream?

:fish:

**Comment by liam-middlebrook** [comment]
I'm working on it now (that comments from ~5 minutes ago)
