### ISSUE TITLE
Recheck on-demand Participation page

### ISSUE THREAD

**Issue by LinkSlayer64** [decause/hflossk#183]
Instead of having the participants page check and dynamically create the page every time you load it, it loads a static version of the page cached on the server. The page will instead have a button that when clicked, will tell the python script to rescrape the pages, and recreate the page on the server.
Besides that, there should be some way to have this function run automatically every hour or so.

I have no clue if this is possible with the current setup (I'm avoiding using a database as decause mentioned)

**Comment by decause** [comment]
The participants page re-checks everytime it is loaded.
Caching pages adds a level of complexity to the site that I do not want students to deal with when they are running the server locally.

Thank you for the suggestions though :)
