### ISSUE TITLE
Add GitCheatsheet in /oer

### ISSUE THREAD

**Issue by DAWacker** [decause/hflossk#34]

**Comment by Zanarama** [comment]
http://threebean.org/presentations/gitflow/#/step-1

**Comment by Qalthos** [comment]
assuming you're talking about the file added in 52368778c312f29558955d5056b657cf44a8f261, it's done. If you're talking about git-flow, that's also done (d413c38f82085fc67cc9a77a08cf0d6ca9ef1903).
