### ISSUE TITLE
Section to allow students to submit links (with approval?) would be way cool.

### ISSUE THREAD

**Issue by Nolski** [decause/hflossk#363]
So when I find links with awesome vim tutorials such as :

https://www.youtube.com/watch?v=SkdrYWhh-8s
and
http://learnvimscriptthehardway.stevelosh.com/

I want to add them to OER but there is no easy/obvious way to do so without making pretty significant code changes. Maybe a tiny board for students to submit links would be cool. Opinions? @decause?

**Comment by liam-middlebrook** [comment]
In https://github.com/liam-middlebrook/hflossk/commit/77c52f43b74d43ca879b651b4ce09e705293004f I just decided to create a txt file that would contain the following:
- Title
- Description
- Link

For now with how hflossk is setup I think that's the simplest way to do things. That way to propose a new resource people only need add a file to which directory it fits under.

**Comment by Nolski** [comment]
The setup is a bit strange since hflossk isn't backed by a database but instead uses a bunch of config (yaml?) files for keeping track of this. I think having a txt or some other config file seems reasonable and if students want to add to it, they can submit pull requests for that. It seems to be inline with how most other modifications to hflossk were managed (unless things have changed since I took the course).

**Comment by liam-middlebrook** [comment]
As far as I'm aware the resources section is powered by a script that just scrubs the `hflossk/static/books` directory for books, and so on. Which seems like the simplest way to add new resources (given that a section already exists).

**Comment by decause** [comment]
@Nolski There is a new /videos section where you can add your videos (for now.) Check develop branch.
