### ISSUE TITLE
scripts/yaml_lint.py only lints files ending in .yaml

### ISSUE THREAD

**Issue by liam-middlebrook** [decause/hflossk#413]
This _could_ be an issue if for some reason people needed to change site.yaml.fall2013 or another file that has a suffix after `.yaml` This isn't something that necessarily should be fixed, but it's important that we're aware of this. @rossdylan stumbled upon this on the first commit in #410

**Comment by ryansb** [comment]
I don't think this is important, though I will add ".yml" as a yaml suffix.
