### ISSUE TITLE
Use a Student class to provide calculated properties

### ISSUE THREAD

**Issue by ryansb** [decause/hflossk#420]
There are a few places now where we execute some [logic](https://github.com/decause/hflossk/blob/01ade3be0de03bfee3a0c41e60c51939337f646b/hflossk/participants.py#L72) and add properties to students. It'd be better if we could do something like this.

```
class Student(object):
    @property
    def participant_page(self):
        return "/blogs/{year}/{term}/{uname}".format(......)
```

This will require a fair amount of changes to existing code, so before doing this we should work on #419

**Comment by mansam** [comment]
I definitely agree with this approach. There's enough going on with the student that it should be a class rather than a dictionary.

**Comment by ryansb** [comment]
See migrated issue on ofCourse repo.
