### ISSUE TITLE
tox error on windows

### ISSUE THREAD

**Issue by wilfriedE** [decause/hflossk#474]
After running tox on windows, I get this error:
<code>
_______________________________________summary____________________________________
ERROR:   py27: InvocationError: C:\Python27\python2.7.exe -mvirtualenv --setuptools --python C:\Users\Wilfried EH.virtualenvs\hflossk\Scripts\python2.7.EXE py27 (see C:\users\Wilfried EH\hflossk.tox\py27\log\py27-0.log) ERROR:   py33: InterpreterNotFound: python3.3 ERROR:   pep8: InvocationError: C:\Python27\python2.7.exe -mvirtualenv --setuptools --python C:\Python27\python2.7.exe pep8 (see C:\users\Wilfried EH\hflossk.tox\pep8\log\pep8-0.log)</code>

**Comment by ryansb** [comment]
The likely problem here is that `pep8` isn't in your path.

**Comment by ryansb** [comment]
This is an environment configuration issue.
