### ISSUE TITLE
Have a master RSS feed for students.

### ISSUE THREAD

**Issue by liam-middlebrook** [decause/hflossk#494]
@ralphbean mentioned possibly tracking github activity in addition to blogposts.
@ryansb mentioned something about using fedmsg in conjunction with this.

**Comment by decause** [comment]
This issue should get migrated to ofcourse upstream repo.

Still high priority.

@Nolski please add.

**Comment by ryansb** [comment]
Split into ryansb/ofCourse#38 and ryansb/ofCourse#29 (already existed)
