### ISSUE TITLE
Assign homework with Github issues

### ISSUE THREAD

**Issue by Nolski** [decause/hflossk#495]
I was thinking it might be kind of cool to have a tool for the professor to assign issues to all students in a specific class as a way of assigning homework. 

Here are some specifics of the process.

Professor wants to create homework. They specify title, class name (stored in yaml somewhere?), and an issue message written in markdown. 
- Script creates and assigns an issue to each student in that class.
- Script creates page on HFOSS website with due date and stuff.
- Possibly hook up to students page to see what homework has been submitted through PR.

**Comment by Nolski** [comment]
This might be a cool thing to work on at SFD.

**Comment by ryansb** [comment]
I don't think this would be a good use case, since each issue can have only one assignee and I feel like automated issue spam would drown out actual issues.

**Comment by liam-middlebrook** [comment]
The only way I could see that happening is through mentions, but I'm not sure they have the same notification properties that assignments do.

**Comment by Nolski** [comment]
Github has tagging. Why not tag all homework issues with homework? These are things that should end up being "fixed" or "resolved" once the student submits them anyways. While it may end up causing issue bloat, that's kind of the point isn't it? Students should be fixing issues with their pull requests.

@liam-middlebrook I think mentions generally will do email notifications.

**Comment by dxa4481** [comment]
I think it's a little unreasonable to have to tag every student, but if you could get every student in an [organization](https://github.com/blog/674-introducing-organizations) there are [team mentions](https://github.com/blog/1121-introducing-team-mentions) that can make this more reasonable. 

One issue with this however, is github will automatically close out issues if your commit message is crafted at the issue. I could see students closing out the issue by accident. Unless of course PR were only accepted after the assignment is past it's due.

**Comment by decause** [comment]
If this is still something you're interested in seeing, then we should migrate this ticket to either ofcourse or the respective content repo if you so choose.

**Comment by ryansb** [comment]
I don't think this is a good way to assign homework, so I'd be -1 on adding it to ofCourse.
