### ISSUE TITLE
Site.py is no longer PEP8 compliant

### ISSUE THREAD

**Issue by liam-middlebrook** [decause/hflossk#500]
In this commit by @decause https://github.com/decause/hflossk/commit/00c6cb09ad9e7ce66b56d0a43774e50c8a82e6c5 on line 81 there are more than 89 characters. This caused the commit to break the TravisCI PEP8 tests.

**Comment by ryansb** [comment]
:crying_cat_face:

**Comment by liam-middlebrook** [comment]
Fixed in https://github.com/decause/hflossk/commit/fd7e44c9682e38f6d4afcb53ad9b418ad98b35dc
