### ISSUE TITLE
Fork me on Github Button unclickable

### ISSUE THREAD

**Issue by kocsenc** [decause/hflossk#541]
On the main header on the right there is a `Fork me on GitHub button`.

The button seems to only be text and doesn't redirect to GitHub repo as expected.

**Comment by liam-middlebrook** [comment]
It appears the only the `GitHub` is a link. This can be noted in [hflossk/templates/master.mak:line-36](https://github.com/decause/hflossk/blob/master/hflossk/templates/master.mak#L36)

```
Fork me on <a target="_blank" href="http://github.com/decause/hflossk" class="navbar-link">Github</a>
```
