### ISSUE TITLE
Handle malformed YAML more sanely

### ISSUE THREAD

**Issue by ryansb** [decause/hflossk#569]
Instead of throwing 500 on malformed YAML, the site should display the students in the class with correct yaml files.

For malformed yaml it should either:
- Display an alert
- Replace tiles for students with bad YAML files with the message from the YAML parser.

**Comment by decause** [comment]
@ryansb 

I love this. Status? How can I help?

**Comment by ryansb** [comment]
Considering only putting the fix in new-hflossk, should be done soonish.
