### ISSUE TITLE
GnuPG Encrypted Grades

### ISSUE THREAD

**Issue by citruspi** [decause/hflossk#640]
CC: @ralphbean @rossdylan @thequbit @mansam @alexanderkyte @chorn

As a couple students mentioned last night, students aren't aware of their grades. @decause does contact students who aren't doing well, and anyone who he hasn't contacted is looking at a B or better, but there's still a lot of uncertainty, especially with the introduction of the plus/minus system.

One solution would be to use MyCourses, but let's be honest, MyCourses is a piece of shit.

I'd like to propose an alternative; GnuPG encrypted grades.

The idea is that as part of the First Flight assignment, students would create a 4096[0] bit GnuPG key pair. There would be a class which would cover GnuPG and it's usage. At the end of the class there would be a key signing party.

Students' grades would be kept up to date and uploaded to the class website. Each student's grade would **encrypted**, **signed**, and **armored**. Encrypted to make sure that grades are confidential, signed to make sure grades are only updated by @decause, and armored to make them viewable in the browser.

Perhaps @ryansb and @liam-middlebrook could add functionality to their command line tool which would simplify the process of updating and publishing grades. The publication of a student's grades in an unencrypted format or the publication of @decause's private key would have dire consequences - if the process could be automated[1] to prevent human error, all the better.

In addition to the increase in transparency by allowing students to see how they are doing in class, it would provide students with an introduction to the usage of and best practices for GnuPG, an important tool in the police state we're quickly approaching.

Any feedback is appreciated.

&mdash; @citruspi

P.S. I'll be submitting this issue to the repositories for both HFOSS and AdvFOSS. I'd like to see it implemented in both classes, but I realize that it may be implemented differently for each class or implemented for one class first as a trial and I think having separate issues for each class is important.

[0] Perhaps, for the AdvFOSS class, we could make it even more interesting. In the class where GnuPG is covered, students would also learn to patch GnuPG to increase the key size beyond 4096 bits and then recompile GnuPG.

[1] Aside, of course, from the entry of the passphrase for the private key, because no one would create a private key without a passphrase, right?

**Comment by alexanderkyte** [comment]
I've been working on a distributed payment protocol based around currency,
optional decaying decaying, It operates in a quasi-p2p manner through pgp
over imap. As reliable as your inbox.

I could tune knobs to make decause pay out grades (maybe a "quiz persona"
and a "hw persona") and students not afford to send grades to eachother
(infinite tariff). I would write it in C# for mono to make it cross
platform. I will leave it to mac owners to use xamarin to publish it. I can
do android.

Their grades stay in the email accounts they make wherever they
want(student email possible. ) Its fully student-owned. A linux daemon that
saves to a folder is also possible. I might give decause a script that
automates grade signing, and also saves to a reliable place. This would
need to be entered into mycourses manually if necessary. (TA labor?)

To clarify, we are making a private chain of trust with decause having the
authoritative key.

**Comment by citruspi** [comment]
@alexanderkyte,

The issue is being moved to the ofCourse repository at the request of @ryansb.

You should repost your comment there.

&mdash; @citruspi
